@startuml
skinparam dpi 200
left to right direction

actor "사용자" as User
actor "관리자" as Admin

frame "YUJU HOTEL(호텔 예약 시스템)" {
    frame "사용자 기능" {
        User --> (회원가입)
        User --> (로그인)
        User --> (객실 소개 페이지)
        (객실 소개 페이지) --> (예약하기)
        (예약하기) --> (결제하기)

        frame "마이페이지" {
            User --> (마이페이지 접속)
            (마이페이지 접속) --> (예약 조회)
            (마이페이지 접속) --> (비밀번호 변경)
            (마이페이지 접속) --> (회원 탈퇴)
        }
    }
    

    frame "관리자 기능" {
        Admin --> (예약 관리)
        (예약 관리) --> (예약 조회)
        (예약 관리) --> (예약 취소)

        Admin --> (객실 관리)
        (객실 관리) --> (객실 수정)
        Admin --> (매출 현황 조회)
    }
}
@enduml